#!D:\Adria Tisnawati A\Matkul Polindra\Semester6\Automatic_Exam_Trust_Score\Automatic-Exam-Trust-Score\audio-env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
